#!/bin/sh
mkdir -p bin

export CFLAGS="-include `readlink -f runtime/em-shell.h` -g"
export EM_LDFLAGS="--pre-js ../em-shell/js/pre.js --js-opts 0 `readlink -f runtime/em-shell.c` --js-library `readlink -f runtime/em-shell.js`"
export KBUILD_VERBOSE=1
export ARCH=em 
export CROSS_COMPILE=em

sh -c "cd ../em-busybox && make -j8 && mkdir -p bin" && cp ../em-busybox/busybox bin
